import { createInterface } from "node:readline/promises";
import { existsSync } from "node:fs";
import { mkdir, writeFile } from "node:fs/promises";
import { homedir } from "node:os";
import { dirname, join } from "node:path";

import yaml from "js-yaml";

import { GitHubClient, resolveAuthenticatedUser } from "../github/index.js";
import { NotFoundError } from "../github/errors.js";

const DEFAULT_RUNNER = "claude";
const DEFAULT_CLAUDE_MODEL = "claude-opus-4-7";
const DEFAULT_CODEX_API_KEY_ENV = "OPENAI_API_KEY";
const DEFAULT_TOKEN_ENV = "GITHUB_TOKEN";

export type InitFlags = {
  token: string | undefined;
  runner: string | undefined;
  model: string | undefined;
  apiKeyEnv: string | undefined;
  repo: string | undefined;
  force: boolean;
  configPath: string;
};

type RepoInfo = {
  full_name: string;
};

async function prompt(rl: ReturnType<typeof createInterface>, question: string): Promise<string> {
  const answer = await rl.question(question);
  return answer.trim();
}

async function validateToken(token: string): Promise<string> {
  const client = new GitHubClient(token);
  return resolveAuthenticatedUser(client);
}

async function validateRepo(token: string, repo: string): Promise<void> {
  const client = new GitHubClient(token);
  const [owner, name] = repo.split("/");
  if (owner === undefined || name === undefined || owner === "" || name === "") {
    throw new Error(`Invalid repo format: "${repo}". Expected owner/repo`);
  }
  try {
    await client.request<RepoInfo>(`/repos/${owner}/${name}`);
  } catch (err) {
    if (err instanceof NotFoundError) {
      throw new Error(`Repo not found or token lacks access: ${repo}`, { cause: err });
    }
    throw err;
  }
}

function buildConfigYaml(
  token: string,
  runner: string,
  model: string,
  apiKeyEnv: string,
  repo: string,
): string {
  const reposDir = join(homedir(), ".otto", "repos");
  const worktreesDir = join(homedir(), ".otto", "worktrees");

  type RunnerEntry = { type: string; model?: string };
  const runnerEntry: RunnerEntry =
    runner === "codex"
      ? { type: "codex", model }
      : { type: "claude", model };

  const config = {
    otto: {},
    github: {
      tokenEnvVar: token === "" ? DEFAULT_TOKEN_ENV : "OTTO_GITHUB_TOKEN",
      repos: [repo],
    },
    workspace: {
      reposDir,
      worktreesDir,
    },
    agent: {
      default: runner,
      runners: {
        [runner]: runnerEntry,
      },
    },
  };

  const lines: string[] = [
    "# Otto configuration — generated by otto init",
    "# Edit this file to add more repos, runners, or tune polling settings.",
    "",
  ];

  if (token !== "") {
    // Emit a comment so the user knows where the env var value came from
    lines.push(`# The GitHub token was saved as OTTO_GITHUB_TOKEN during otto init.`);
    lines.push(`# Set that variable in your shell before running: export OTTO_GITHUB_TOKEN=<your-token>`);
    if (runner === "codex") {
      lines.push(`# Codex runner requires ${apiKeyEnv} in your environment.`);
    }
    lines.push("");
  }

  lines.push(yaml.dump(config, { lineWidth: 120 }));
  return lines.join("\n");
}

async function collectToken(flags: InitFlags, rl: ReturnType<typeof createInterface>): Promise<{ token: string; login: string }> {
  if (flags.token !== undefined) {
    process.stdout.write("Validating GitHub token...\n");
    const login = await validateToken(flags.token);
    process.stdout.write(`  Authenticated as: ${login}\n`);
    return { token: flags.token, login };
  }

  for (;;) {
    const token = await prompt(rl, "GitHub personal access token: ");
    if (token === "") {
      process.stdout.write("  Token is required.\n");
      continue;
    }
    process.stdout.write("Validating token...\n");
    try {
      const login = await validateToken(token);
      process.stdout.write(`  Authenticated as: ${login}\n`);
      return { token, login };
    } catch (err) {
      process.stdout.write(`  Invalid token: ${err instanceof Error ? err.message : String(err)}\n`);
    }
  }
}

async function collectRunner(flags: InitFlags, rl: ReturnType<typeof createInterface>): Promise<string> {
  if (flags.runner !== undefined) {
    if (flags.runner !== "claude" && flags.runner !== "codex") {
      throw new Error(`Unknown runner "${flags.runner}". Valid values: claude, codex`);
    }
    return flags.runner;
  }

  for (;;) {
    const answer = await prompt(rl, `Runner [claude/codex] (default: ${DEFAULT_RUNNER}): `);
    const runner = answer === "" ? DEFAULT_RUNNER : answer;
    if (runner === "claude" || runner === "codex") return runner;
    process.stdout.write("  Enter 'claude' or 'codex'.\n");
  }
}

async function collectModel(
  flags: InitFlags,
  runner: string,
  nonInteractive: boolean,
  rl: ReturnType<typeof createInterface>,
): Promise<{ model: string; apiKeyEnv: string }> {
  const defaultModel = runner === "codex" ? "gpt-4o" : DEFAULT_CLAUDE_MODEL;

  if (runner === "codex") {
    let apiKeyEnv: string;
    if (flags.apiKeyEnv !== undefined || nonInteractive) {
      apiKeyEnv = flags.apiKeyEnv ?? DEFAULT_CODEX_API_KEY_ENV;
    } else {
      const answer = await prompt(
        rl,
        `OpenAI API key env var (default: ${DEFAULT_CODEX_API_KEY_ENV}): `,
      );
      apiKeyEnv = answer === "" ? DEFAULT_CODEX_API_KEY_ENV : answer;
    }
    const model = flags.model ?? defaultModel;
    return { model, apiKeyEnv };
  }

  // claude runner
  let model: string;
  if (flags.model !== undefined || nonInteractive) {
    model = flags.model ?? DEFAULT_CLAUDE_MODEL;
  } else {
    const answer = await prompt(rl, `Claude model (default: ${DEFAULT_CLAUDE_MODEL}): `);
    model = answer === "" ? DEFAULT_CLAUDE_MODEL : answer;
  }
  return { model, apiKeyEnv: "" };
}

async function collectRepo(
  flags: InitFlags,
  token: string,
  rl: ReturnType<typeof createInterface>,
): Promise<string> {
  if (flags.repo !== undefined) {
    process.stdout.write(`Validating repo ${flags.repo}...\n`);
    await validateRepo(token, flags.repo);
    process.stdout.write("  Repo is accessible.\n");
    return flags.repo;
  }

  for (;;) {
    const repo = await prompt(rl, "First repo to watch (owner/repo): ");
    if (repo === "") {
      process.stdout.write("  Repo is required.\n");
      continue;
    }
    process.stdout.write(`Validating ${repo}...\n`);
    try {
      await validateRepo(token, repo);
      process.stdout.write("  Repo is accessible.\n");
      return repo;
    } catch (err) {
      process.stdout.write(`  ${err instanceof Error ? err.message : String(err)}\n`);
    }
  }
}

export async function runInit(flags: InitFlags): Promise<void> {
  const configPath = flags.configPath;

  if (!flags.force && existsSync(configPath)) {
    process.stderr.write(
      `Config already exists at ${configPath}.\nPass --force to overwrite.\n`,
    );
    process.exitCode = 1;
    return;
  }

  const isNonInteractive =
    flags.token !== undefined && flags.runner !== undefined && flags.repo !== undefined;

  const rl = createInterface({
    input: process.stdin,
    output: process.stdout,
    terminal: !isNonInteractive,
  });

  try {
    process.stdout.write("\notto init — first-run setup wizard\n\n");

    const { token, login } = await collectToken(flags, rl);
    const runner = await collectRunner(flags, rl);
    const { model, apiKeyEnv } = await collectModel(flags, runner, isNonInteractive, rl);
    const repo = await collectRepo(flags, token, rl);

    const configYaml = buildConfigYaml(token, runner, model, apiKeyEnv, repo);

    await mkdir(dirname(configPath), { recursive: true });
    await writeFile(configPath, configYaml, { encoding: "utf8", flag: flags.force ? "w" : "wx" });

    process.stdout.write("\nConfig written to: " + configPath + "\n");
    process.stdout.write("\nSummary:\n");
    process.stdout.write(`  Authenticated user: ${login}\n`);
    process.stdout.write(`  Runner: ${runner} (model: ${model})\n`);
    if (runner === "codex" && apiKeyEnv !== "") {
      process.stdout.write(`  OpenAI API key env: ${apiKeyEnv}\n`);
    }
    process.stdout.write(`  Watching: ${repo}\n`);
    process.stdout.write("\nTo start the daemon, run:\n");
    process.stdout.write("  otto start\n\n");
  } finally {
    rl.close();
  }
}
